"""
backend/app/api/v1/endpoints/pricing.py
--------------------------------------
Dynamic pricing, optimization, simulation, and pricing curve endpoints (Module 6).
"""

from fastapi import APIRouter, Depends, HTTPException, Query, status
from typing import List, Optional
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.services import optimization_service, simulation_service
from app.schemas.optimization import (
    OptimizePriceRequest,
    PricingRecommendationResponse,
    SingleSimulationRequest,
    SingleSimulationResponse,
    RangeSimulationRequest,
    RangeSimulationResponse,
    PricingCurveResponse,
)

router = APIRouter()


@router.get(
    "/recommendations",
    response_model=List[PricingRecommendationResponse],
    summary="List Pricing Recommendations",
)
def get_pricing_recommendations(
    status: Optional[str] = Query(None, description="Status filter: 'pending' | 'approved' | 'rejected' | 'applied'"),
    product_id: Optional[str] = Query(None, description="Product UUID or external SKU ID"),
    db: Session = Depends(get_db),
):
    """Retrieve pricing recommendations generated by optimization."""
    return optimization_service.list_pricing_recommendations(db, status=status, product_identifier=product_id)


@router.post(
    "/optimize",
    response_model=PricingRecommendationResponse,
    status_code=status.HTTP_200_OK,
    summary="Optimize Price for Product",
)
def optimize_price(
    request: OptimizePriceRequest,
    db: Session = Depends(get_db),
):
    """
    Run multi-constraint price optimization for a product under PROFIT_MAX, REVENUE_MAX, or BALANCED objective.
    """
    try:
        return optimization_service.optimize_product_price(db, request)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Optimization failed: {e}",
        )


@router.post(
    "/simulate",
    response_model=SingleSimulationResponse,
    status_code=status.HTTP_200_OK,
    summary="Simulate Single Price Point",
)
def simulate_price(
    request: SingleSimulationRequest,
    db: Session = Depends(get_db),
):
    """
    Evaluate expected demand, revenue, profit, margin, and guardrail constraints for a candidate price.
    """
    try:
        return simulation_service.simulate_single_price(db, request)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Simulation failed: {e}",
        )


@router.post(
    "/simulate-range",
    response_model=RangeSimulationResponse,
    status_code=status.HTTP_200_OK,
    summary="Simulate Range of Candidate Prices",
)
def simulate_price_range(
    request: RangeSimulationRequest,
    db: Session = Depends(get_db),
):
    """
    Evaluate candidate prices across a min/max price range to identify revenue and profit optima.
    """
    try:
        return simulation_service.simulate_price_range(db, request)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Range simulation failed: {e}",
        )


@router.get(
    "/{product_id}/curve",
    response_model=PricingCurveResponse,
    summary="Get Pricing Curve (Demand, Revenue, Profit)",
)
def get_pricing_curve(
    product_id: str,
    db: Session = Depends(get_db),
):
    """
    Generate curve data points across price spectrum for interactive charts.
    """
    try:
        return simulation_service.get_pricing_curve(db, product_id)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Pricing curve generation failed: {e}",
        )
